# Generated by Django 3.1.7 on 2021-03-19 11:31

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
