# Generated by Django 3.1.12 on 2021-06-27 06:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0002_auto_20210627_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Entry',
        ),
    ]
