# Generated by Django 3.1.13 on 2021-07-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20210627_1219'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['name'], name='record_entr_name_52c523_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['email'], name='record_entr_email_4ba09e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['phone_number'], name='record_entr_phone_n_9556e6_idx'),
        ),
    ]
